---
title: "Young Model Exploration"
date: "`r Sys.Date()`"
author: "R. Cura & S. Rey-Coyrehourcq"
output:
  rmdformats::readthedown:
    highlight: kate
    thumbnails: true
    lightbox: true
    gallery: true
---


```{r knitr_init, echo=FALSE, cache=FALSE}
library(knitr)
library(rmdformats)

## Global options
options(max.print="75")
opts_chunk$set(echo=FALSE,
	             cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)
```

```{r load packages}
source("ggplot2_formatter.R")
library(readr)
options("readr.num_columns" = 0)
library(dplyr)
#library(GGally)
library(tidyr)
library(ggplot2)
library(ggthemes)
library(gridExtra)

```

```{r load data, cache = TRUE, echo = FALSE}
resultsDF <- read_csv("../SimOutputs/plan_complet_result.csv")
```

```{r plot_theming}
theme_tmd <- function(){
  tmd <- theme(axis.text=element_text(size=6),
               axis.title=element_text(size=8),
               strip.text = element_text(size = 8),
               plot.title=element_text(size =16,face="bold", hjust = -0.09,margin=margin(b=-15))
               )
}

```

```{r summary, echo = FALSE}
summaryDF <- resultsDF %>%
  select(-(seed:probaDeathByOvercrowding))

 summaryDF <- as.data.frame(sapply(summaryDF, summary)) %>%
  mutate(Stat = row.names(.)) %>%
  select(Stat, initialPopulation:thistime) %>%
  tbl_df()
#kable(summaryDF)
```

```{r scattermatrix, eval = TRUE}
meanDF <- resultsDF %>%
  group_by(probaMove, probaBirth, probaDeath, probaDeathByOvercrowding) %>%
  summarise_each(funs(mean), initialPopulation:thistime) %>%
  rename(mv = probaMove, bth = probaBirth, dth = probaDeath, dby = probaDeathByOvercrowding)

plotDF <- resultsDF %>%
  rename(mv = probaMove,
         bth = probaBirth,
         dth = probaDeath,
         dby = probaDeathByOvercrowding,
         pop = initialPopulation)


# abc <- ggplot(meanDF, aes(x = population, occupiedWorld)) +
#   geom_point(alpha = 0.2, size=0.2) +
#   facet_grid(mv + dth ~ bth + dth, labeller = labeller(.rows = label_both, .cols = label_both))
# plot(abc)
```

```{r prepa plot4_1, cache = TRUE, eccho = FALSE}
plot1DF <- plotDF %>%
  filter(dth != 0.66, mv ==1) %>%
  rename(`Proba. de mort` = dth) %>%
  rename(`Proba. de déplacement` = mv)
```

```{r plot4_1, echo = FALSE}
plot4_1 <-ggplot(plot1DF, aes(x = population, y = occupiedWorld)) +
  geom_point(alpha = 1, size=0.01) +
  scale_x_continuous(name = "Taille de la population", labels = human_numbers) +
  scale_y_continuous(name = "Part de l'espace occupé",  labels = scales::percent) +
  facet_grid(`Proba. de déplacement`~`Proba. de mort`,
             labeller = labeller(.rows = label_both, .cols = label_both)) +
  theme_tmd() +
  ggtitle("(1)")

#plot(plot4_1)
```

```{r prepa plot4_2, cache = TRUE, echo = FALSE}
generations_list <- list.files("../SimOutputs/GenAlgo/", pattern = "*.csv")
fullDF <- data_frame()
for (currentGen in generations_list){
  fullDF <- fullDF %>%
    bind_rows(read_csv(sprintf("../SimOutputs/GenAlgo/%s", currentGen)))
}

corrFullDF <- fullDF %>%
  mutate(popObj = 1E6 - popObj) %>%
  mutate(occupiedObj = 1 - occupiedObj)

labelDF <- data_frame(x =  numeric(), y = numeric(), cluster = character())
labelDF[1,] <- c(2.2E5, 1, "A")
labelDF[2,] <- c(0.4E5, 1, "B")
labelDF[3,] <- c(3E5, 0.15, "C")
labelDF[4,] <- c(0.11E5, 0.58, "D")
labelDF <- labelDF %>%
  mutate_each(funs(as.numeric), -cluster)

clusterDF <- data_frame(xmin=numeric(), xmax=numeric(), ymin=numeric(), ymax=numeric(), cluster=character())
clusterDF[1,] <- c(1.9E5, 2.1E5, 0.85, 1, "A")
clusterDF[2,] <- c(0.5E5, 2E5, 0.95, 1.05, "B")
clusterDF[3,] <- c(2E5, 3.3E5,0, 0.1, "C")
clusterDF[4,] <- c(-500, 0.15E5,0, 0.55, "D")
clusterDF <- clusterDF %>%
  mutate_each(funs(as.numeric), -cluster)


longDF <- corrFullDF %>%
  mutate(A = ifelse(popObj >= 1.9E5 & popObj <= 2.1E5 & occupiedObj >= 0.85 & occupiedObj <= 1, TRUE, FALSE)) %>%
  mutate(B = ifelse(popObj >= 0.5E5 & popObj <= 2E5 & occupiedObj >= 0.95 & occupiedObj <= 1.05, TRUE, FALSE)) %>%
  mutate(C = ifelse(popObj >= 2E5 & popObj <= 3.3E5 & occupiedObj >= 0 & occupiedObj <= 0.1, TRUE, FALSE)) %>%
  mutate(D = ifelse(popObj >= -500 & popObj <= 0.15E5 & occupiedObj >= 0 & occupiedObj <= 0.55, TRUE, FALSE)) %>%
  gather(key = Cluster, value = bob, A:D) %>%
  filter(bob) %>%
  select(-bob) %>%
  mutate(Cluster = factor(Cluster))

```

```{r plot4_2}

plot4_2 <- ggplot() +
    geom_rect(data = clusterDF,
              aes(xmin = xmin,
                  xmax =  xmax,
                  ymin= ymin,
                  ymax = ymax,
                  fill = cluster),
              alpha = 0.4) +
  geom_label(data = labelDF,
             aes(x = x, y =  y, label = cluster, fill = cluster, stroke = cluster),
             colour = "black", fontface = "bold", size=3,  alpha = 0.6) +
  geom_point(data = corrFullDF, aes(x = popObj, y = occupiedObj), size = 0.1, alpha = 1) +
  guides(fill = FALSE, label = FALSE) +
  scale_x_continuous(name = "Taille de la population", limits = c(-1000, 350E3), labels = human_numbers) +
  scale_y_continuous(name = "Part de l'espace occupé", labels = scales::percent) +
  theme_tmd() +
  ggtitle("(2)")

#plot(plot4_2)

```

```{r prepa plot4_3, cache = TRUE}
tidyDF <- longDF %>%
  rename(`Génération` = `evolution$generation`) %>%
  mutate(`Génération` = (`Génération` / max(`Génération`))) %>%
  gather(key = Param, value = Value, probaMove:probaDeathByOvercrowding, `Génération`) %>%
  mutate(Param = ifelse(Param == "probaDeathByOvercrowding", "Proba. de mort\npar suffocation", Param)) %>%
  mutate(Param = ifelse(Param == "probaMove", "Proba. de\ndéplacement", Param)) %>%
  mutate(Param = ifelse(Param == "probaBirth", "Proba. de\nnaissance", Param)) %>%
  mutate(Param = ifelse(Param == "probaDeath", "Proba. de\nmort", Param)) %>%
  mutate(Param = factor(Param, levels=c("Proba. de\ndéplacement", "Proba. de\nmort", "Proba. de mort\npar suffocation", "Proba. de\nnaissance", "Génération"))) %>%
  filter(Param != "Génération")
```

```{r plot4_3}
plot4_3 <- ggplot(data = tidyDF, aes(Cluster, Value,  fill = Cluster)) +
  geom_violin(alpha = 0.7) +
  facet_grid(.~Param, scale = "free_y", space="free") +
  guides(fill=FALSE) +
  scale_x_discrete(name = "Classe") +
  scale_y_continuous(name = "Valeur de\nparamètre") +
  theme_tmd() +
  ggtitle("(3)")

#plot(plot4_3)
```

```{r allPlots print, fig.width=5.31, fig.height=6}
fig4 <- arrangeGrob(plot4_1, plot4_2, plot4_3, ncol = 1)
#plot(fig4)
```

```{r allPlots save, cache=TRUE }
ggsave(plot = fig4, filename = "figure4.pdf", width = 5.31, height = 6)
ggsave(plot = fig4, filename = "figure4.png", width = 5.31, height = 6,  dpi = 300)
ggsave(plot = fig4, filename = "figure4.tiff", width = 5.31, height = 6,  dpi = 300)
```
